name: genopets
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.1+1
  flutter_triple: ^1.2.5
  intl: ^0.17.0
  shared_preferences:
  dio:
  get: 
  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.13
  firebase_auth: ^3.3.15
  google_sign_in: ^5.0.0
  flutter_svg: ^1.0.3
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/images/logo.png"
    - .env

