# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Bitrise App"
  lane :distribute do
    build_android_app(task: "clean bundleRelease")
    firebase_app_distribution(
      app: "1:497642312492:android:3938fd9f5a8c60a8e01289",
      service_credentials_file: "genopets-5a359-4925a5717ccb.json",
      release_notes: "Deployed to Google Play",
      android_artifact_type: "AAB",
      firebase_cli_path: "/usr/local/bin/firebase",
      apk_path: "../build/app/outputs/bundle/release/app-release.aab",
    )
  end
end
